version: 2
updates:
  - package-ecosystem: 'github-actions'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
      day: 'monday'
