name: Publish WordPress Plugins

on:
  push:
    branches:
      - canary

  workflow_dispatch:

jobs:
  publish-plugins:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4']
        plugins:
          [
            'wds-headless-acf',
            'wds-headless-algolia',
            'wds-headless-blocks',
            'wds-headless-core',
            'wds-headless-gravityforms',
            'wds-headless-seo'
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Create /dist
        run: mkdir dist

      - name: Bundle
        run: |
          cd backend/plugins/${{ matrix.plugins }}
          zip ${{ matrix.plugins }}.zip * -r -x node_modules/\* -x vendor/\* -x .git/\*
          mv ${{ matrix.plugins }}.zip ../../../dist

      - name: Publish
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: 'dist/${{ matrix.plugins }}.zip'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: '.git/,node_modules/,vendor/'

      - name: Install
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: 'backend/plugins/${{ matrix.plugins }}'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.PLUGIN_PATH }}
          EXCLUDE: '.git/,node_modules/,vendor/'
