name: Publish NPM Packages

on:
  release:
    types: [created]
    paths:
      - 'packages/next/package.json'

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use NPM 7
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Publish next
        uses: JS-DevTools/npm-publish@v1
        with:
          access: 'public'
          check-version: TRUE
          dry-run: TRUE
          package: 'packages/next/package.json'
          token: ${{ secrets.NPM_TOKEN }}
