name: Publish

on:
  push:
    branches:
      - canary

  workflow_dispatch:

jobs:
  publish-plugins:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4']
        plugins:
          [
            'wds-headless-acf',
            'wds-headless-algolia',
            'wds-headless-blocks',
            'wds-headless-core',
            'wds-headless-gravityforms',
            'wds-headless-seo'
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Create /dist
        run: mkdir dist

      - name: Bundle
        run: |
          cd backend/plugins/${{ matrix.plugins }}
          zip ${{ matrix.plugins }}.zip * -r -x node_modules/\* -x vendor/\* -x .git/\*
          mv ${{ matrix.plugins }}.zip ../../../dist

      - name: Publish
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: 'dist/${{ matrix.plugins }}.zip'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: '.git/,node_modules/,vendor/'

      - name: Install
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: 'backend/plugins/${{ matrix.plugins }}'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.PLUGIN_PATH }}
          EXCLUDE: '.git/,node_modules/,vendor/'

  publish-theme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Create /dist
        run: mkdir dist

      - name: Bundle
        run: |
          cd backend/themes/wds-headless-theme
          zip wds-headless-theme.zip * -r
          mv wds-headless-theme.zip ../../../dist

      - name: Publish
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: 'dist/wds-headless-theme.zip'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: '.git/,node_modules/,vendor/'

      - name: Install
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: 'backend/themes/wds-headless-theme'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.THEME_PATH }}
          EXCLUDE: '.git/,node_modules/,vendor/'

  publish-storybook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use NPM 7
        run: npm i -g npm@latest

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build-storybook

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: storybook/storybook-static
          target-folder: storybook

  publish-docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_PRIVATE_KEY }}

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use NPM 7
        run: npm i -g npm@latest

      - name: Setup Git
        run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}

      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          cd docs
          npm install

      - name: Lint
        run: |
          cd docs
          npm run lint

      - name: Publish
        env:
          USE_SSH: true
          GIT_USER: ${{ secrets.GIT_USER_NAME }}
        run: |
          cd docs
          npm run publish

  publish-to-wpe-prod:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.OS }}-composer-

      - name: Authorize Composer with WDS packagist server
        run: echo '${{ secrets.COMPOSER_AUTH }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install dependencies
        run: composer install

      - name: Rsync to dev
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: './'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: '.git*,.env,composer.json,composer.lock,auth.json,package.json,package-lock.json,node_modules/,/uploads/,/upgrade/,/advanced-cache.php,/object-cache.php,/debug.log,/mysql.sql,/mu-plugins/mu-plugin.php,/mu-plugins/wpengine-common/,/mu-plugins/wpe-wp-sign-on-plugin.php,/mu-plugins/wpe-wp-sign-on-plugin/,/mu-plugins/slt-force-strong-passwords.php,/mu-plugins/force-strong-passwords/,/mu-plugins/wpengine-security-auditor.php,/mu-plugins/wpe-elasticpress-autosuggest-logger/'
