name: Publish WordPress Plugins

on:
  push:
    branches:
      - canary

  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4']
        plugins:
          [
            'wds-headless-acf',
            'wds-headless-algolia',
            'wds-headless-blocks',
            'wds-headless-core',
            'wds-headless-gravityforms',
            'wds-headless-seo'
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Install ${{ matrix.plugins }}
        run: |
          cd plugins/${{ matrix.plugins }}
          composer validate --strict
          composer install --prefer-dist --no-progress

      - name: Lint
        run: composer run-script lint

      - name: Bundle ${{ matrix.plugins }}
        run: |
          cd plugins
          zip ${{ matrix.plugins }}.zip ${{ matrix.plugins }} -r -x node_modules/\* -x vendor/\* -x .git/\* -O ../${{ matrix.plugins }}

  publish:
    needs: test_build
    runs-on: ubuntu-latest
    steps:
      - name: Publish to public server
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: 'plugins/*.zip'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: '.git/,node_modules/,vendor/'
