name: Publish WordPress Plugins

on:
  push:
    branches:
      - canary

  workflow_dispatch:

jobs:
  publish-plugins:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4']
        plugins:
          [
            'wds-headless-acf',
            'wds-headless-algolia',
            'wds-headless-blocks',
            'wds-headless-core',
            'wds-headless-gravityforms',
            'wds-headless-seo'
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.OS }}-composer-

      - name: Create /dist
        run: mkdir dist

      - name: Validate composer.json
        run: |
          cd plugins/${{ matrix.plugins }}
          composer validate --strict

      - name: Install dependencies
        run: |
          cd plugins/${{ matrix.plugins }}
          composer install --prefer-dist --no-progress

      - name: Lint plugin
        run: |
          cd plugins/${{ matrix.plugins }}
          composer run-script lint

      - name: Bundle plugin
        run: |
          cd plugins/${{ matrix.plugins }}
          zip ${{ matrix.plugins }}.zip * -r -x node_modules/\* -x vendor/\* -x .git/\*
          mv ${{ matrix.plugins }}.zip ../../dist

      - name: Publish plugin
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-v -a -z --delete'
          SOURCE: 'dist/${{ matrix.plugins }}.zip'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: '.git/,node_modules/,vendor/'
